### ISSUE TITLE
DockPanelTabs not rendered when DockPanel count < 2

### ISSUE THREAD

**Issue by pm64** [Andersen27/Photino.Blazor.Docking#8]
Hey @Andersen27, I noticed a small issue in the latest commit: when a DockPanelTabs only contains a single DockPanel, the DockPanelTabs isn't rendered.

So the following displays as expected:

```
<DockPanelTabs CurrentTabIndex="0">
    <DockPanel Id="index" />
    <DockPanel Id="counter" />
</DockPanelTabs>
```

But the following results in the display of a blank area where DockPanelTabs should be:

```
<DockPanelTabs CurrentTabIndex="0">
    <DockPanel Id="index" />
</DockPanelTabs>
```

Let me know if you need any further diagnostic info, etc..

**Comment by Andersen27** [comment]
The current docking mechanism assumes automatic container change during the docking process: for example, if table with two panels exists and one of these two panels was detached, then the table container will destroyed due to the fact that it is unnecessary to display a single panel. Instead of DockPanelTabs, the DockPanel component is inserted directly. It works similarly for DockPanelSplit. This is necessary to avoid a non-stop containers count increase.
So if only one panel is needed in your layout, insert it without wrapping in DockPanelTabs.

The markup inside DockPanelHost currently works only as setting the initial panels layout.
Maybe something will change with dynamic tabbing.

I will close issue with "as designed" reason.

**Comment by pm64** [comment]
Understood, thanks @Andersen27 for the explanation.
